USE Sample2;
GO

/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [PersonID]
      ,[Name]
  FROM [Sample2].[dbo].[tblPerson1]



  DELETE FROM tblPerson1 WHERE PersonID = 1;

  /** SET IDENTITY COLUMN INSERT ON THAT MEANS SET INCREMENT OF IDENTITY COLUMN**/
  SET IDENTITY_INSERT tblPerson1 ON;

  /** DOING INSERT IN SEPECIFIC IDENTITY COLUMN **/
  INSERT INTO dbo.tblPerson1 (PersonID,[Name]) VALUES (1,'Muhammad Punk');
   
  /** SET IDENTITY COLUMN INSERT OFF THAT MEANS SET INCREMENT BACK ON IDENTITY COLUMN**/
  SET IDENTITY_INSERT tblPerson1 OFF;


   DELETE FROM dbo.tblPerson1;
   /**WHEN TRY TO INSERT INTO TABLE IDENETITY INCREAMENT BY ON PERVIOUS VALUE EVEN IF YOU REMOVE ALL TABLE DATA**/
   INSERT INTO dbo.tblPerson1 ([Name]) VALUES ('Muhammad Punk');
   
   
   DELETE FROM dbo.tblPerson1;

   /**WHEN USE METHOD DOWNBLOW IT RESERT IDENTITY COLUMN IN THE tblPerson1 TABLE**/
   
   DBCC CHECKIDENT(tblPerson1, RESEED, 0);
   
   /**WHEN TRY TO INSERT INTO TABLE IDENETITY INCREAMENT BY ON PERVIOUS VALUE EVEN IF YOU REMOVE ALL TABLE DATA**/
   
   INSERT INTO dbo.tblPerson1 ([Name]) VALUES ('Muhammad Punk');
