CREATE TABLE tblTest1 
(
	ID int IDENTITY (1,1),
	[Value] nvarchar(20)
)

CREATE TABLE tblTest2 
(
	ID int IDENTITY (1,1),
	[Value] nvarchar(20)
)

/** CREATE TRIGGER TriggerName on TableName For Action **/
CREATE TRIGGER trForInsert on tblTest1 FOR INSERT
AS
BEGIN
	INSERT INTO tblTest2 ([Value]) VALUES ('Y');
END

INSERT INTO tblTest1 ([Value]) VALUES ('X');

SELECT * FROM tblTest1;
SELECT * FROM tblTest2;

/** SELECT LAST GENERATE IDENTITY VALUE IN THE SAME SESSION (CONNECTION) WITHIN THE SAME SCOPE **/
SELECT SCOPE_IDENTITY();

/** SELECT LAST GENERATE IDENTITY VALUE IN THE SAME SESSION (CONNECTION) ACROSS ANY SCOPE **/
SELECT @@IDENTITY;

/** SELECT LAST OF TABLE GENERATE IDENTITY VALUE ACROSS SESSION (CONNECTION) ACROSS ANY SCOPE **/
SELECT IDENT_CURRENT('tblTest2');