USE [Hackerrank];
GO

SELECT TOP (1) [CITY], LEN([CITY]) FROM [Easy].[STATION]
ORDER BY LEN([CITY]), [CITY];

SELECT TOP (1) [CITY], LEN([CITY]) FROM [Easy].[STATION]
ORDER BY LEN([CITY]) DESC, [CITY];